[MorseMap]
QQ=a
QA=b
QR=c
QQQ=d
QQA=e
QQR=f
QAQ=g
QAA=h
QAR=i
QRQ=j
QRA=k
QRR=l
AQ=m
AA=n
AR=o
AQQ=p
AQA=q
AQR=r
AAQ=s
AAA=t
AAR=u
ARQ=v
ARA=w
ARR=x
RQ=y
RA=z
RAAA={Ctrl}
RR={Space}
RQAQ={Backspace}
RQAA={Enter}
RQAR={Escape}
RQQ=1
RQA=2
RQR=3
RAQ=4
RAA=5
RAR=6
RRQ=7
RRA=8
RRR=9
RRRRR=0
RRRRQ=.
RRRRA=,
RRQQ=A
RRQA=B
RRQR=C
RRQQQ=D
RRQQA=E
RRQQR=F
RRQAQ=G
RRQAA=H
RRQAR=I
RRQRQ=J
RRQRA=K
RRQRR=L
RRAQ=M
RRAA=N
RRAR=O
RRAQQ=P
RRAQA=Q
RRAQR=R
RRAAQ=S
RRAAA=T
RRAAR=U
RRARQ=V
RRARA=W
RRARR=X
RRRQ=Y
RRRA=Z
RAAQQ=à
RRRAAQQ=À
RQRQ={Tab}
RQRA={Delete}
RQRR={Home}
RQRRRQ={End}
RQRRA={PgUp}
RQRRR={PgDn}
RQRRRA=+{Tab}
RQRQQ={Left}
RQRQA={Down}
RQRQR={Right}
RQRRQ={Up}
RQAQA=^{Backspace}
QAQAQA={ToggleADB}
RQQA={LButton}
RQQR={RButton}
RRRR={WheelDown}
RQARA={Reload}
ARAR={WheelLeft}
RARA={WheelRight}
RQRAR={AndroidPower}
QRQR={MacroKey}
QAQA={TeamsKey}
RQQRAA={TobiiF2}
RQQQ={ToggleLButton}

RQRQQRQ={ToggleBluetooth}

RQRQQR={ConnectBTDevice}

R={RepeatLast}
Q={Volume_Down}
A={Volume_Up}
ARAR={Volume_Mute}
RARAR={SiteKey}
RARAQQR=^
RARAQAQ=~
RARRRQ=´
RARRQAQ=`
RAQQ=ç
RRRAQQ=Ç
RAAR={FKey}
RAQR={MKey}
RAAQ={Shift}
RAQA={Alt}
RARAQ={SysKey}
RARRQ=/
RARRA=;
RARRR=-
RARRQQ==
RARRQA=[
RARRQR=]
RARRAQ='
; ' (fecha aspa para o editor)
RRRRRR={QuotesLeft}
RAQAQA={ToggleCapsLock}
RQQRQ={AppSwitch}
AQAQ={WheelUp}
RARRAR=\
QAQR={SpotifyKey}
QQAA={LWin}
QQAR={WinMenu}
RAQAR={EmailKey}
RQAAA={CadastroKey}
RAQQR={VisionKey}
RAQRA={CustomKey}
QAAQ={TextKey}
RAQAA={ToggleLock}